/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Layer = IDL.Record({
  'imageData' : IDL.Text,
  'name' : IDL.Text,
  'locked' : IDL.Bool,
  'visible' : IDL.Bool,
});
export const Frame = IDL.Record({ 'layers' : IDL.Vec(Layer) });
export const Project = IDL.Record({
  'id' : IDL.Text,
  'height' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'frames' : IDL.Vec(Frame),
  'width' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'loadProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'saveProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(Frame)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Layer = IDL.Record({
    'imageData' : IDL.Text,
    'name' : IDL.Text,
    'locked' : IDL.Bool,
    'visible' : IDL.Bool,
  });
  const Frame = IDL.Record({ 'layers' : IDL.Vec(Layer) });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'height' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'frames' : IDL.Vec(Frame),
    'width' : IDL.Nat,
  });
  
  return IDL.Service({
    'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'loadProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'saveProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(Frame)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };