/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Frame { 'layers' : Array<Layer> }
export interface Layer {
  'imageData' : string,
  'name' : string,
  'locked' : boolean,
  'visible' : boolean,
}
export interface Project {
  'id' : string,
  'height' : bigint,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'frames' : Array<Frame>,
  'width' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'createProject' : ActorMethod<[string, string, bigint, bigint], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'loadProject' : ActorMethod<[string], Project>,
  'saveProject' : ActorMethod<
    [string, string, bigint, bigint, Array<Frame>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];